---
title: "Geolocate Addresses"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
  html_notebook:
    fig_width: 6
    toc: yes
    toc_float: yes
---
The goal of this R Notebook is to Geolocate addresses from a well water sampling campaign. To do this, we will access the Open Streat Maps API using an R Function modified from an example presented in [this blog](https://datascienceplus.com/osm-nominatim-with-r-getting-locations-geo-coordinates-by-its-address/).

#Setup
```{r setup}
#Clear memory
rm(list=ls(all=TRUE))

#Load Required Packages
library(mapsapi)
library(sf)
library(parallel)
library(tidyverse)


#Define working directory and database location
working_dir<-"//nfs/njones-data/Research Projects/Private Wells/Harvey/flow_analysis/"

#Api Key  (Do not leave this here or upload to github)
api_key <- "NA" 
```

#Create API Function
```{r function}
#Create function to access Google API
google_api<-function(UID=NULL, address = NULL, api_key = NULL){
  
  #Download xml file
  doc<-mp_geocode(address, key=api_key)
  
  #Convert to points
  pnts<-mp_get_points(doc)
  
  #Convert to coordinates
  xy<-st_coordinates(pnts)
  
  #export coordinates with Unique ID
  data.frame(UID, xy)
}

```
#Well Water Sample Locations
Its go time!

```{r Samples}
#Read well sample location .csv
df<-read_csv(paste0(working_dir,"locations.csv"))

#Create wrapper function with error handling
fun<-function(n){
  tryCatch(google_api(UID     = df$Key[n],
                      address = df$Sample_Address[n], 
                      api_key = api_key), 
           error=function(e) data.frame(UID=df$Key[n], 
                                        X=0, 
                                        Y=0))
}

#run wrapper function
t0<-Sys.time()
x1<-mclapply(X=seq(  1, 400),      FUN=fun, mc.cores = 8)
x2<-mclapply(X=seq(401, 800),      FUN=fun, mc.cores = 8)
x3<-mclapply(X=seq(801,1200),      FUN=fun, mc.cores = 8)
x4<-mclapply(X=seq(1200,nrow(df)), FUN=fun, mc.cores = 8)
tf<-Sys.time()
save.image("output.RData")

#Collect data
output1<-bind_rows(x1)
output2<-bind_rows(x2)
output3<-bind_rows(x3)
output4<-bind_rows(x4)
output<-rbind(output1,output2, output3, output4)
colnames(output)<-c("Key", "X","Y")

#Merge output with df
df<-left_join(df, output, by="Key")
df<- df %>% select(-Lat, -Long)

#Write.csv
write.csv(df, paste0(working_dir, "address_output.csv")) 

# output
save.image(paste0(working_dir,"output.RData"))
```

