---
title: "Geolocate Addresses"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
  html_notebook:
    fig_width: 6
    toc: yes
    toc_float: yes
---
The goal of this R Notebook is to Geolocate addresses from a well water sampling campaign. To do this, we will access the Open Streat Maps API using an R Function modified from an example presented in [this blog](https://datascienceplus.com/osm-nominatim-with-r-getting-locations-geo-coordinates-by-its-address/).

#Setup
```{r setup}

rm(list=ls(all=TRUE))

#Load Required Packages
library(jsonlite)
library(tidyverse)

#Define working directory and database location
working_dir<-"//nfs/njones-data/Research Projects/Private Wells/Harvey/flow_analysis/"
```

#Create function and test 
```{r function}
#Create function to access Open Street map API.
osm_fun <- function(UID=NULL, address = NULL){
  
  #If address is blank, return blank df
  if(suppressWarnings(is.null(address)))
    return(data.frame(UID = UID,
                      address= address,
                      lon = -9999, 
                      lat = -9999))
  #Else, contact API and search for address
  tryCatch(
    d <- jsonlite::fromJSON( 
      gsub('\\@addr\\@', gsub('\\s+', '\\%20', address), 
           'http://nominatim.openstreetmap.org/search/@addr@?format=json&addressdetails=0&limit=1')
    ), error = function(c) return(data.frame(UID = UID,
                                       address= address,
                                       lon = -9999, 
                                       lat = -9999))
  )
  
  #If not in OSM, return blank df
  if(length(d) == 0) return(data.frame(UID = UID,
                                       address= address,
                                       lon = -9999, 
                                       lat = -9999))
  
  #Make system sleep for 1 second [OSM API requirement]
  Sys.sleep(1)
  
  #Export data!
  return(data.frame(UID = UID,
                    address= address,
                    lon = as.numeric(d$lon), 
                    lat = as.numeric(d$lat)))
}

#As it turns out, OSM is a bit picky about its input. Below is an example. 
test<-osm_fun(UID     = 1,
              address = "1, Park Place Ave, Annapolis, Anne Arundel County, MD, 21401, USA")

test2<-osm_fun(UID     =2, 
               address = "1552, Ritchie Ln, Annapolis, Anne Arundel County, MD, 21401, USA")

test3<-osm_fun(UID     =3, 
               address = "13019, Chavile, Cypress, Harris County, TX, 77429, USA")


```
#Well Water Sample Locations
Its go time!

```{r Samples}
#Read well sample location .csv
df<-read_csv(paste0(working_dir,"locations.csv"))

#Make Corrections to data
#Change Cypress Zip Code
df<-df %>%
  mutate(Sample_Zip = ifelse(str_sub(Sample_Address,
                                     str_locate(Sample_Address, ",")[,1]+2,
                                     str_locate(Sample_Address, "TX")[,1]-3) == "Cypress", 
                             77433,
                             Sample_Zip))

#for testing
df<-df[1:10,]

#Clean up dataset
df<-df %>% 
  #Remove Lat and long collumns
  select(-Lat, -Long) %>%
  #Remove noaddresses
  filter(Sample_Address!="No address") %>%
  #create address input
  mutate(Sample_Address = paste0( #address number
                                  str_sub(Sample_Address,
                                          1,
                                          str_locate(Sample_Address, " ")[,1]-1),
                                  #Add comma and space
                                  paste(", "),
                                  #Road Name
                                  str_sub(Sample_Address,
                                          str_locate(Sample_Address, " ")[,1]+1,
                                          str_locate(Sample_Address, ",")[,1]-1),
                                  paste(","),
                                  #Town
                                  str_sub(Sample_Address,
                                          str_locate(Sample_Address, ",")[,1]+1,
                                          str_locate(Sample_Address, "TX")[,1]-3),
                                  #Add County and state
                                  paste0(", ", Sample_County, " County, Texas"), 
                                  #Add zip
                                  paste0(", ", Sample_Zip),
                                  #Add country! [USA! USA! USA!]
                                  ", USA"))
  
#Create wrapper function
fun<-function(n){
  osm_fun(UID =     df$Key[n],
          address = df$Sample_Address[n])
}

#run wrapper function
x<-lapply(seq(1,10), fun)
output<-bind_rows(x)
output

```

